### ISSUE TITLE
高负载情况下Consumer数应与Partition数保持一致

### ISSUE THREAD

**Issue by shadyxu** [superhj1987/kafka-sudy#1]
负载低的情况下可以每个线程消费多个partition。但负载高的情况下，Consumer 线程数最好和 Partition 数量保持一致。如果还是消费不过来，应该再开 Consumer 进程，进程内线程数同样和分区数一致。

**Comment by superhj1987** [comment]
嗯 高负载下的确应该这样，多谢提醒。
